### ISSUE TITLE
将Json内容作为ConfigMap挂载到容器app目录

### ISSUE THREAD

**Issue by bidianqing** [bidianqing/DockerApp#1]
appsettings.yaml
``` 
apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings
  namespace: bidianqing
data:
  appsettings.Test.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": "*",
      "ValuesConfiguration": {
        "Message": "The configuration is working!" 
      },
      "Environment": "Test"
    }
```

deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerapp-deployment
  namespace: bidianqing
spec:
  selector:
    matchLabels:
      app: dockerapp
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: dockerapp
    spec:
      containers:
      - name: dockerapp
        image: bidianqing/dockerapp:1.0
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Test
        ports:
        - containerPort: 5077
        volumeMounts:
        - name: config-volume
          mountPath: /app/appsettings.Test.json
          subPath: appsettings.Test.json
      volumes:
      - name: config-volume
        configMap:
          name: appsettings
```
如果mountPath写成`/app`，会覆盖app目录下的内容，直接就把程序文件给覆盖了，解决办法是使用subPath。使用subPath的弊端是无法热更新
